### List Exercises
GET http://localhost:8080/api/exercises
Accept: application/json

### Create Exercise
POST http://localhost:8080/api/exercises
Content-Type: application/json
Accept: application/json

{
  "name": "Push Up",
  "description": "An exercise for upper body strength",
  "photo_url": "lksdalskldaklsd",
  "video_url": "11111111"
}

### Delete Exercise
DELETE http://localhost:8080/api/exercises/1
Accept: application/json

### Get Exercise
GET http://localhost:8080/api/exercises/2
Accept: application/json

### Update Exercise
PUT http://localhost:8080/api/exercises/1
Content-Type: application/json
Accept: application/json

{
  "name": "Modified Push Up 3",
  "description": "An updated description for upper body strength exercise"
}