### Get all workouts
GET http://localhost:8080/api/workouts
Accept: application/json

### Create a new workout
POST http://localhost:8080/api/workouts
Content-Type: application/json
Accept: : application/json

{
  "name": "Morning Run 2",
  "order": 1,
  "training_plan_id": 1
}

### Delete a workout
DELETE http://localhost:8080/api/workouts/1
Accept: application/json

### Get a workout by ID
GET http://localhost:8080/api/workouts/5
Accept: application/json

### Update a workout
PUT http://localhost:8080/api/workouts/5
Content-Type: application/json
Accept: application/json

{
  "name": "Evening Run Updated",
  "order": 2,
  "training_plan_id": 1
}